import sys
import os
import json
import numpy as np
from manim import *

# Path setup logic (same as before)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
for path in (SCRIPT_DIR, PROJECT_ROOT):
    if path not in sys.path:
        sys.path.append(path)

# Imports
from prism_lib.visuals.neural_net import PrismNeuralNetwork
from prism_lib.components import PrismSlide
from prism_lib.theme import BACKGROUND_COLOR, ACCENT_COLOR, TEXT_COLOR

# Load Data
DATA_PATH = os.path.join(PROJECT_ROOT, "data.json")
with open(DATA_PATH, "r") as f:
    SCENE_DATA = json.load(f)

class ConceptScene(MovingCameraScene):
    def construct(self):
        self.camera.background_color = BACKGROUND_COLOR

        # --- NEW: PRISM BRANDING INTRO ---
        # Yeh har video ke start mein chalega
        brand_text = Text("PRISM", font_size=80, weight=BOLD, color=ACCENT_COLOR)
        brand_sub = Text("Generated by AI", font_size=24, color=GRAY).next_to(brand_text, DOWN)
        
        self.play(Write(brand_text), run_time=1)
        self.play(FadeIn(brand_sub))
        self.wait(0.5)
        self.play(FadeOut(brand_text), FadeOut(brand_sub))
        # ---------------------------------

        # Ab main content shuru hoga
        title_text = SCENE_DATA.get("title", "Topic Name")
        narration = SCENE_DATA.get("narration", {})
        visual = SCENE_DATA.get("visual_config", {})
        vtype = visual.get("type") or visual.get("visual_type") or "Slide"
        params = visual.get("params", {})

        # --- LOGIC BRANCHING ---
        if vtype == "Slide":
            # SCENARIO A: General Topic (History, Physics, etc.)
            subtitle = params.get("subtitle") or narration.get("visual_desc") or ""
            slide = PrismSlide(title_text, subtitle)
            self.play(slide.animate_intro())
            self.wait(1)
            
            # Show Body Text if available
            if "body_text" in params:
                body = Text(params["body_text"], font_size=28, color=TEXT_COLOR)
                body.next_to(slide.title, DOWN, buff=1.0)
                self.play(Write(body))
                self.wait(2)
            
            # Outro
            outro = narration.get("outro") or ""
            if outro:
                outro_text = Text(outro, font_size=24, color=GRAY).to_edge(DOWN)
                self.play(FadeIn(outro_text))
                self.wait(1)
            return

        # SCENARIO B: AI/Neural Network Topic
        # (Yeh code tabhi chalega agar topic AI wala ho)
        layers = params.get("layer_sizes") or [3, 5, 2]
        inputs = SCENE_DATA.get("inputs", [1.0] * layers[0])
        expected_output = SCENE_DATA.get("expected_output", [0.0] * layers[-1])

        slide = PrismSlide(title_text, narration.get("intro", "Simulating flow..."))
        self.play(slide.animate_intro())
        self.wait(0.5)
        self.play(slide.animate.scale(0.8).to_corner(UL, buff=0.8), run_time=1.2)

        # Draw Network
        nn = PrismNeuralNetwork(layer_sizes=layers, layer_to_layer_buff=1.3)
        nn.scale(1.2).to_edge(RIGHT, buff=1.0)
        
        self.play(nn.create(), run_time=2)
        
        # Simulate Thinking
        self.play(nn.set_activations([
            inputs, 
            [0.5]*layers[1], # Dummy hidden values
            expected_output
        ]))
        self.wait(2)