from manim import *

class GenScene(Scene):
    def construct(self):
        title = Text("Simple Harmonic Motion", font_size=48)
        self.play(Write(title))
        self.wait(1)
        title.to_edge(UP)
        self.wait(1)
        eq = MathTex(r"x = A \sin(\omega t + \phi)")
        self.play(Write(eq))
        self.wait(1)
        eq.next_to(title, DOWN)
        self.wait(1)
        circle = Circle(radius=1, color=BLUE)
        circle.move_to(ORIGIN)
        self.play(Create(circle))
        self.wait(1)
        arrow = Arrow(start=LEFT, end=RIGHT, color=YELLOW)
        arrow.next_to(circle, DOWN)
        self.play(Create(arrow))
        self.wait(1)
        self.play(FadeOut(arrow))
        self.wait(1)
        self.play(FadeOut(circle))
        self.wait(1)
        self.play(FadeOut(eq))
        self.wait(1)
        self.play(FadeOut(title))
        self.wait(1)